<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise Async Await</title>
    <style>
        *{
            margin: 10px;
            padding: 5px;
        }
        span{font-size: 25px;}
        h4{color: rgb(0, 89, 255);}
        h5{color: rgb(56, 122, 56);}
        p{background-color: rgba(166, 199, 99, 0.904); margin-top: 0; margin-bottom: 0; font-size: 20px;}
        #given{background-color: rgb(166, 199, 99); margin-top: 0; margin-bottom: 0; font-size: 20px;}
        pre{background-color: rgb(226, 183, 130); color: rgb(37, 16, 16);}
        .reason{
            color: rgb(240, 64, 93);
            font-size: 20px;
        }
    </style>
</head>
<body>
    <p><span>Q1.</span> Write one example explaining how you can write a callback function.</p>
    <h4>Solution:</h4>
    <pre>
        function greet(b,a){
        console.log(`Hi! ${a()} Good ${b}`)
        }
        greet("morning",function(){
        return "Name";
        });
    </pre>
    <h5>Result :</h5>
    <pre>
        Hi! Name Good morning
        <span class="reason"> The anonymous function that is defined and passed as the second argument to the gree() function is a callback function.</span>
    </pre>
    <hr>
    <p><span>Q2.</span> "Write a callback function to print numbers from 1 to 7, in which 1 should be printed after 1 sec, 2 should be printed after 2 sec, 3 should be printed after 3 sec, and so on.
        Explain callback hell.
        Numbers 1 2 3 4 5 6 7"</p>
        <h4>Solution:</h4>
        <pre>
          setTimeout(() => {
            console.log(1);
            setTimeout(() => {
              console.log(2);
              setTimeout(() => {
                console.log(3);
                setTimeout(() => {
                  console.log(4);
                  setTimeout(() => {
                    console.log(5);
                    setTimeout(() => {
                      console.log(6);
                      setTimeout(() => {
                        console.log(7);
                      }, 1000);
                    }, 1000);
                  }, 1000);
                }, 1000);
              }, 1000);
            }, 1000);
          }, 1000);
        </pre>
    <h5>Result :</h5>
    <pre>
        1
        2
        3
        4
        5
        6
        7
        <span class="reason"> Each number is printed after 1 second.
        Here series of nested setTimeout() functions that are called one after the other and each delayed by 1 second
        creates a Callback Hell. The code becomes difficult to read and maintain,
        especially as the number of nested functions increases.</span>
    </pre>
    <hr>
    <p><span>Q3.</span> "Write the promise function to print numbers from 1 to 7, in which 1 should be printed after 1 sec, 2 should be printed after 2 sec, 3 should be printed after 3 sec, and so on.
        Numbers 1 2 3 4 5 6 7"</p>
    <h4>Solution:</h4>
    <pre>
        let demo = Promise.resolve();
        for(let i=1;i<=7;i++){
            setTimeout(()=>{
                demo = demo.then(()=> console.log(i));
            }, i*1000)
        }
    </pre>
    <h5>Result :</h5>
    <pre>
        1
        2
        3
        4
        5
        6
        7
    </pre>
    <hr>
    <p><span>Q4.</span> "Create a promise function accepting an argument, if yes is passed to the function then it should go to resolved state and print Promise Resolved, and if nothing is passed 
        then it should go to reject the state and catch the error and print Promise Rejected "</p>
    <h4>Solution:</h4>
    <pre>
        function print(a){
        return new Promise((resolve,rejected)=>{
            if (a==="yes"){
                resolve("Promise Resolved");
            }
            else{
                rejected("Promise Rejected");
            }
            })
        }
        print()//first case
            .then((result)=>{console.log(result)})
            .catch((error)=>{console.log(error)})
            print("yes")//second case
            .then((result)=>{console.log(result)})
            .catch((error)=>{console.log(error)})
        </pre>
    <h5>Result :</h5>
    <pre>
        "Promise Rejected"//first case

        "Promise Resolved"//second case
    </pre>
    <hr>
    <p><span>Q5.</span> Create examples to explain callback function</p>
    <h4>Solution:</h4>
    <pre>
        function outer(subject, inner) {
        console.log(`My ${subject} handson ${inner()}`);
        }

        outer('Closure', function() {
        return "is completed.";
        });
    </pre>
    <h5>Result :</h5>
    <pre>
        My Closure handson is completed.
        <span class="reason"> Here the callback function is the anonymous function passed as the second argument to the outer function.</span>
    </pre>
    <hr>
    <p><span>Q6.</span> Create examples to explain callback hell function</p>
    <h4>Solution:</h4>
    <pre>
        function F1(cb1){
        console.log("F1 is called.");
        cb1();
        }
        function F2(cb2){
        console.log("F2 is called.");
        cb2();
        }
        function F3(cb3){
        console.log("F3 is called.");
        cb3();
        }
        function F4(cb4){
        console.log("F4 is called.");
        cb4();
        }
    
      F1(()=>{
        F2(()=>{
          F3(()=>{
            F4(()=>{
            });
          });
        });
      });
    </pre>
    <h5>Result :</h5>
    <pre>
        "F1 is called."
        "F2 is called."
        "F3 is called."
        "F4 is called."
        <span class="reason"> When F1() is called, it passes a callback to F2() and so on.
        This creates a "callback hell" because the code is deeply nested and hard to read and maintain.</span>
    </pre>
    <hr>
    <p><span>Q7.</span> Create examples to explain promise function</p>
    <h4>Solution:</h4>
    <pre>
        function check(x){
        return new Promise((resolve,reject)=>{
          if(x>=10){
            resolve("your number is OK");
          }
          else{
            reject("your number is less than 10");
          }
        })
      }
      check(6)//first case
      .then((res)=>{console.log(res)})
      .catch((err)=>{console.log(err)})

      check(12)//second case
      .then((res)=>{console.log(res)})
      .catch((err)=>{console.log(err)})
    </pre>
    <h5>Result :</h5>
    <pre>
        "your number is less than 10"
        "your number is OK"
        <span class="reason"> In the First case the promise gets to reject state and .catch() function print the error.
        In the Second case the promise gets to resolve state and .then() function print the result.</span>
    </pre>
    <hr>
    <p><span>Q8.</span> Create examples to explain async await function</p>
    <h4>Solution:</h4>
    <pre>
        let demo = new Promise((res)=>{
        setTimeout(()=>{
          res("promise resolved")
        },2000)
      })
      
      async function sample(){
       let result = await demo;
        console.log(result);
        console.log("Its done.");
      }
      
      sample()
    </pre>
    <h5>Result :</h5>
    <pre>
        promise resolved
        Its done.
        <span class="reason"> Promise demo() resolves after a delay of 2 seconds using setTimeout().
        The async function sample is called but it will wait untill the promise is resolved as the await keyword is used.</span>
    </pre>
    <hr>
    <p><span>Q9.</span> Create examples to explain promise.all function</p>
    <h4>Solution:</h4>
    <pre>
        const pr1 = new Promise((resolve, reject) => {
            setTimeout(() => {
              resolve('pr1');
            }, 2000);
          });
          
          const pr2 = new Promise((resolve, reject) => {
            setTimeout(() => {
              resolve('pr2');
            }, 4000);
          });
          
          Promise.all([pr1, pr2])
            .then(results => {
              console.log(results[0] + " and " + results[1]+" come togather");
            })
            .catch(error => {
              console.error(error);
            });
    </pre>
    <h5>Result :</h5>
    <pre>
        pr1 and pr2come togather
        <span class="reason"> Pr1() and Pr2() has their respective delay to get resolve state for setTimeout().
        Then promise.all() function holds the process of output untill boath the promises complete successfully.</span>
    </pre>
</body>
</html>